### ISSUE TITLE
1284p synch issues

### ISSUE THREAD

**Issue by Andon-A** [nootropicdesign/arduino-tvout-ve#4]
I'd like to use the 1284p for a project, as it has the highest sram and higher sram means higher resolution.

I, of course, immediately ran into the timing issues with using this microcontroller and my programming knowledge, let alone AVR knowledge, is nowhere near the task of fixing it. I've attempted to fiddle with the variables in video_properties.h but have had no meaningful results.

I am using the [MightyCore](https://github.com/MCUdude/MightyCore) bootloader and so far everything seems to be working as it should.

Has there been any investigation into just why the 1284/1284p have these issues?

**Comment by nootropicdesign** [comment]
I think the first question is whether you connected everything to the right 1284p pins. What board are you using?

**Comment by Andon-A** [comment]
It's naked, with an 8mHz crystal. I can get video to show, but it has *horrible* vertical synch. I'll see if I can capture something of it.

I have a 644 and some 16mHz and 20mHz crystals ordered, to see if they change anything.

**Comment by nootropicdesign** [comment]
The default implementation of TVout assumes a 16MHz clock, unless you adjusted that for 8MHz. But an 8MHz system isn't fast enough to run the code fast enough to render. You may have better luck with 16MHz xtal.

**Comment by Andon-A** [comment]
Popped in the 16MHz crystal and magic! It looks like everything is running excellently.

Thanks a lot!

**Comment by Andon-A** [comment]
Alright, so. Jumped the gun a little bit.

Video *output* is working fine. But I know so little about what is going on in the initOverlay() portion of the NTSC demo to know where I should connect things.

From what I gather the Uno/328p uses Pin 2 with an external interrupt to detect a falling edge and this triggers the start of the scan line for the overlay. What I *don't* know is how to adapt this to the 1284p - That is, what the equivalent pin is, or how to select it and set it up correctly. I tried brute force - Connecting Pin 2 on the VE shield to every pin on the 1284p, but unsurprisingly didn't get any results.

If you have any insight that can be dumbed down to my basic understanding of Arduino/C, it would be greatly appreciated.

**Comment by nootropicdesign** [comment]
You need to use the pin on the 1284p that is assigned to INT0.  Looks like this is PD2 on the 1284p. Also make sure you include in your sketch the interrupt handler for INT0:

```
// Required to reset the scan line when the vertical sync occurs
ISR(INT0_vect) {
  display.scanLine = 0;
}
```

**Comment by Andon-A** [comment]
Running the DemoNTSC with initOverlay() commented out lets me see the output normally and just fine. As expected, the base video is steady and the overlay slides down the screen.

If I uncomment initOverlay() with VSYNCH (D2 on the VE) connected to PD2, I get the base video and intermittent small, slight horizontal lines.

Pins D6 and D8 as labled on the VE are not connected to the 1284p, nor is the potentiometer connected to A2. 

I suspect this is deeper and more complex than just running wires to different pins. While I would love to get the 1284p working with it, it's not super critical. I greatly appreciate the assistance!

**Comment by nootropicdesign** [comment]
Yes, you need other circuit components. This is the code for the Video Experimenter. I did not write the original TVout. See https://code.google.com/archive/p/arduino-tvout/
You need resistors and diodes on the video pin and sync pin to create the correct voltages on the RCA video connector.

**Comment by Andon-A** [comment]
Yep, I'm working specifically with the Video Experimenter. Just trying to get the 1284p working with it. Not knowing intimately how the VE works puts it a bit beyond what I know how to do and I'm not going to put my pet project on you just because you're kind enough to answer my questions.

Going to close this. Thanks a lot for the help!
